---

- name: set up an account on the target machine for the current user
  user: 'name={{ lookup("env","USER") }} shell=/bin/bash groups=adm,sudo,plugdev append=yes state=present'

- name: set up the authorized key of this machine's user
  authorized_key: 'user={{ lookup("env","USER") }} key="{{ item }}"'
  with_file:
    - "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

- name: copy the code to the target machine
  copy: 'src=.. dest=/opt/mfl_api owner={{ lookup("env","USER") }} group={{ lookup("env","USER") }} mode=0644 directory_mode=0644'

- name: update versions of common dependencies via pip before we make our venv
  pip: 'name={{item}} state=latest'
  with_items:
    - pip
    - distribute
    - virtualenv
    - virtualenvwrapper

- name: now install the dependencies that we need
  pip: chdir=/opt/mfl_api requirements=/opt/mfl_api/requirements.txt virtualenv=/opt/mfl_api_virtualenv
