---
- hosts: all
  name: Install MFL API and front-ends
  sudo: True
  roles:
    - common
    - postgresql
    - { role: api, server_name: mfl.azure.slade360.co.ke}
    - { role: frontend, server_name: mfl-public.slade360.co.ke}
